# Generated by Django 4.1.2 on 2022-10-09 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_category_recipe_author_recipe_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cover',
            field=models.ImageField(blank=True, default='', upload_to='recipes/covers/%Y/%m/%d/'),
        ),
    ]
